export const ACTION_CONSTANTS = {
  FETCH_OKRS: {
    SET: "IN_PROGRESS",
    RESET: "SUCCESS",
    FETCH_OKRS_API_DATA: "FETCH_OKRS_API_DATA",
    FETCH_OKRS_API_STATUS: "FETCH_OKRS_API_STATUS",
  },
};
